### ISSUE TITLE
Add support for Parcel v2

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/new#6]
I tested with parcel v2 alpha 1. It nows support ES6 export / import.

**Comment by 3cp** [comment]
We are aware of the alpha release, but decided to skip the early period of Parcel v2 because of seeing some issues raised by early adapters.

We will come back to Parcel definitely.

**Comment by khuongduybui** [comment]
Last time I checked, ES6 module format was the deal breaker.

What's blocking us now?
I may try to pursue this myself if there are no blockers.

**Comment by khuongduybui** [comment]
My current issue is that Parcel doesn't know that my-app.ts/js depends on my-app.html and my-app.css

Did we have a strategy for that before?

**Comment by 3cp** [comment]
We need plugins for all the bundlers to support aurelia conventions. Currently this is done for webpack and gulp.

I have studied parcel and browserify. So I knew roughly what to do. It's just controlling our efforts because Aurelia 2 is changing rapidly. We didn't want to target all bundlers at this stage.

**Comment by khuongduybui** [comment]
Ah ok, I will close this issue then. Thanks for the insight.

**Comment by 3cp** [comment]
We will close this when it's implemented.

**Comment by 3cp** [comment]
Parcel v2 is out with Rust implemented JS parser/transformer (based on swc) and also source maps. Really like the direction.

**Comment by 3cp** [comment]
#74

**Comment by 3cp** [comment]
Merged.
